merchant/config/routes.rb
Rails.application.routes.draw do

  resources :addresses

  resources :orders do 
    member do 
      get :confirm
    end
  end

  resources :order_items

  resources :products

  match "/login" => redirect("/auth/twitter"), as: :login, via: :get
  match "/logout" => "sessions#destroy", as: :logout, via: :get
  match '/auth/:provider/callback', to: 'sessions#create', via: :get

  root to: "products#index"
  

end

merchant/app/models/order_item.rb
class OrderItem < ActiveRecord::Base	
	belongs_to :order
	belongs_to :product
	
	# validates_presence_of :order_id, :product_id
	validates :quantity, numericality: {only_integer: true, greater_than: 0}

	def subtotal
		quantity * product.price
	end

end

merchant/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :load_order, only: [:create]
  before_action :set_order_item, only: [:show, :edit, :destroy]

  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1
  # GET /order_items/1.json
  def show
  end

  # GET /order_items/new
  def new
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
    # @order_item = OrderItem.new(order_item_params)
    # @order_item = OrderItem.new(product_id: params[:product_id], order_id: @order.id)
    # @order_item = @order.order_items.new(quantity: 1, product_id: params[:product_id])
    @order_item = @order.order_items.find_or_initialize_by(product_id: params[:product_id])
    @order_item.quantity += 1

    respond_to do |format|
      if @order_item.save
        # format.html { redirect_to @order_item, notice: 'Order item was successfully created.' }
        format.html {redirect_to @order, notice: 'Successfully added product to cart.'}
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    @order_item = OrderItem.find(params[:id])
    respond_to do |format|
      if order_item_params[:quantity].to_i == 0
        @order_item.destroy
        format.html { redirect_to @order_item.order, notice: 'Order item is removed from cart.'}
        format.json { head :no_content }
      elsif @order_item.update(order_item_params)
        format.html { redirect_to @order_item.order, notice: 'Order item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:product_id, :order_id, :quantity)
    end

    # def load_order
    #   @order = Order.find_or_initialize_by(id: session[:order_id], status: "unsubmmited", user_id: session[:user_id])

    #   if @order.new_record?
    #     @order.save
    #     session[:order_id] = @order.id
    #   end

    #   # begin
    #   #   @order = Order.find(session[:order_id])
    #   # rescue ActiveRecord::RecordNotFound
    #   #   @order = Order.create(status: "unsubmitted")
    #   #   session[:order_id] = @order.id
    #   # end

    #  # @order = Order.find_or_initialize_by_id(session[:order_id], status: 'unsubmitted')
    #  #  if @order.new_record?
    #  #    @order.save!
    #  #    session[:order_id] = @order.id
    #  #  end
    # end

end

merchant/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

merchant/app/views/order_items/_form.html.erb
<%= form_for(@order_item) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- 
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div> -->
  <%= @order_item.product.title %><br>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

merchant/app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

merchant/app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Order</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.product_id %></td>
        <td><%= order_item.order_id %></td>
        <td><%= order_item.quantity %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order item', new_order_item_path %>

merchant/app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_items_path %>

merchant/app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order_item.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<%= link_to 'Remove', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>